language: node_js
sudo: false
branches:
  only:
    - master
    - version-3
node_js:
  - "4"
  - "6"
  - "8"
  - "node"
cache:
  - yarn: true
  - directories:
    - node_modules
    - packages/bundle-parser/node_modules
    - packages/reporter-treemap/node_modules
    - packages/plugin/node_modules
addons:
  apt:
    packages:
      # Required by Electron
      # https://github.com/juliangruber/electron-stream#travis
      - xvfb
before_script:
  # Install packages in subdirectories
  - npm run bootstrap
  # Required by Electron
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  # Building sources
  - npm run build
script:
  - npm run lint
  - npm run test
